### ISSUE TITLE
[BUG] Problem description file is empty when downloaded

### ISSUE THREAD

**Issue by ShinniUwU** [Borovaneca/JudgeFileGenerator#2]
### Description
The current implementation only checks for problem descriptions named "Условия" 
 This causes issues with:
1. The new judge system
2. Contests where the problem description has a different name

Additionally, the downloaded file is 0 bytes, indicating a failed download.

### Current Behavior
- Only searches for "Условия" in resource names
- Even when I include something like ``` if (resource.getString("name").equals("Условия")|| resource.getString("name").equals("Problem Description")) ```Downloads an empty file (0 bytes)

### Expected Behavior
- Check for problem descriptions using multiple common names or patterns
- Successfully download non-empty problem description files

### Code Location
`src/main/java/service/Download.java`, in the `download()` method:

```java
if (resource.getString("name").equals("Условия")) {
    fileId = resource.getString("id");
}
```

### Additional Notes
This issue affects the usability of the tool for international contests and requires immediate attention to ensure proper functionality across various contest formats.

**Comment by Borovaneca** [comment]
```
Even when I include something like if (resource.getString("name").equals("Условия")|| resource.getString("name").equals("Problem Description"))Downloads an empty file (0 bytes)
```

I will add the `Problem Descriptiom` statement.

If you are downloading an empty file, it's not because of the program itself. It's because the user account you are logged in with does not have the necessary permissions to download the file. SoftUni restricts access to certain resources by not allowing the downloading or opening of specific files and videos. Please be aware of this, and before attempting to download any file, ensure that you have the rights to do so,

**Comment by Borovaneca** [comment]
The issue with the "Problem Description" has been fixed with the last update.
